name: Testing

on:
    push:
    pull_request:

jobs:
    code-style:
        name: Check code style
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "8.4"
                    tools: "composer"

            -   name: Install vendors
                run: composer install --prefer-dist

            -   name: Check style on sources
                run: bin/phpcs --standard=src/phpcs-ruleset.xml -n src/

            -   name: Check style on tests
                run: bin/phpcs --standard=tests/phpcs-ruleset.xml -n tests/

    php-stan:
        name: Run PHP-Stan
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "8.4"
                    tools: "composer"

            -   name: Install vendors
                run: composer install --prefer-dist

            -   name: Run php stan
                run: bin/phpstan

    tests:
        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [ '8.4' ]

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_USER: migrator
                    MYSQL_PASSWORD: 'Q1w2e3r4'
                    MYSQL_DATABASE: migrations
                ports:
                    - 3306:3306

        env:
            MYSQL_DSN: mysql:host=127.0.0.1;dbname=migrations
            MYSQL_USER: migrator
            MYSQL_PASSWORD: 'Q1w2e3r4'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: "composer"

            -   name: Install vendors (stable)
                run: composer install --prefer-dist

            -   name: Run tests
                run: bin/phpunit

            -   name: Install vendors (lowest)
                run: composer update --prefer-lowest

            -   name: Run tests
                run: bin/phpunit
